stages:
  - docker-build
before_script:
  - img=registry.docker.quancheng-ec.com:5000/jupyter-odps:`TZ=CST-8 date '+%Y%m%d-%H%M'`
  - hostname -i
  - whoami
build_images:
   stage: docker-build
   script:
    - echo $img
    - if [ "`docker images | awk '/^registry.docker.quancheng-ec.com:5000/ { print $3 }'`" ]; then docker rmi -f $(docker images | awk '/^registry.docker.quancheng-ec.com:5000/ { print $3 }' ); fi
    - echo "Build Docker Image..."
    - docker build --no-cache -t $img .
    - echo "Push Image:" $img " to repository..."
    - docker push $img
   only:
    - master
